shapediver/AppBuilderShared

components/shapediver/platform/ModelCard.module.css, components/shapediver/platform/ModelCard.tsx, components/shapediver/platform/ModelLibrary.tsx, components/shapediver/ui/ParametersAndExportsAccordionComponent.tsx, components/ui/TabsComponent.module.css, components/ui/TabsComponent.tsx, hooks/shapediver/platform/useModelQuery.ts, pages/platform/LibraryPage.module.css, pages/platform/LibraryPage.tsx, store/useShapeDiverStorePlatform.ts, types/store/shapediverStorePlatform.ts, utils/platform.ts
https://shapediver.atlassian.net/browse/SS-7607
=> SS-7607 library page wip

pages/templates/AppBuilderAppShellTemplatePage.tsx
https://shapediver.atlassian.net/browse/SS-7876
=> SS-7876 Fix "appshell" template issue if no right container

components/shapediver/appbuilder/AppBuilderAccordionWidgetComponent.tsx, components/shapediver/ui/AcceptRejectButtons.tsx, hooks/shapediver/appbuilder/useResolveAppBuilderSettings.ts, hooks/shapediver/appbuilder/useSessionWithAppBuilder.ts, hooks/shapediver/parameters/useSortedParametersAndExports.ts, hooks/shapediver/useSession.ts, hooks/shapediver/useSessions.ts, types/components/shapediver/propsExport.ts, types/components/shapediver/propsParameter.ts
https://shapediver.atlassian.net/browse/SS-7919
=> SS-7919 use "parameter validation" resp. "commit mode" setting of model for acceptRejectMode

hooks/shapediver/viewer/interaction/useNodeInteractionData.ts, hooks/shapediver/viewer/interaction/useSelection.ts, hooks/shapediver/viewer/interaction/utils/patternUtils.ts
https://shapediver.atlassian.net/browse/SS-7926
@snabela please review this new logic!
=> SS-7926: adjusted name filtering

components/shapediver/parameter/ParameterSelectionComponent.tsx, hooks/shapediver/viewer/interaction/useSelectManager.ts, hooks/shapediver/viewer/interaction/useSelectManagerEvents.ts, hooks/shapediver/viewer/interaction/useSelection.ts
https://shapediver.atlassian.net/browse/SS-7932
https://shapediver.atlassian.net/browse/SS-7937
https://shapediver.atlassian.net/browse/SS-7936
https://shapediver.atlassian.net/browse/SS-7934
@snabela I combined all the tasks in this PR, as it basically involved adapting the Selection Parameter, and I just did it all at once.
These are all the tasks we wanted to include in this first release. It now works waaaay smoother 😎
=> SS-7937, SS-7932, SS-7936, SS-7934: final changes for selection parameter

components/shapediver/appbuilder/AppBuilderImage.module.css, components/shapediver/appbuilder/AppBuilderImage.tsx, context/AppBuilderContext.ts, context/NotificationContext.ts, hooks/shapediver/viewer/interaction/gumball/useGumball.ts, hooks/shapediver/viewer/interaction/selection/useSelectManagerEvents.ts, hooks/ui/useCustomTheme.ts, pages/appbuilder/AppBuilderPage.tsx, pages/templates/AppBuilderAppShellTemplatePage.tsx, pages/templates/AppBuilderContainerWrapper.tsx, pages/templates/AppBuilderGridTemplatePage.tsx, pages/templates/AppBuilderTemplateSelector.tsx, types/components/shapediver/componentTypes.ts, types/context/appbuildercontext.ts, types/context/notificationcontext.ts, types/pages/appbuildertemplates.ts
https://shapediver.atlassian.net/browse/SS-7974
https://shapediver.atlassian.net/browse/SS-7859
=> SS-7974 Provide rendering hints about container to page templates

components/shapediver/parameter/ParameterGumballComponent.tsx
https://shapediver.atlassian.net/browse/SS-7987
parsing error because I missed an `s` for transformations 😂
=> SS-7987: parsing error

hooks/shapediver/viewer/interaction/gumball/useGumball.ts, hooks/shapediver/viewer/interaction/selection/useSelection.ts, hooks/shapediver/viewer/interaction/useNodeInteractionData.ts, hooks/shapediver/viewer/interaction/utils/patternUtils.ts
https://shapediver.atlassian.net/browse/SS-7980
Everything works as expected already, I'm just not entirely happy with the new `useEffect` call in the outputs loop. Do you have any better idea on how to solve that?
=> SS-7980: activate Gumball if it is only one object

components/shapediver/appbuilder/AppBuilderActionAddToCartComponent.tsx, components/shapediver/appbuilder/AppBuilderActionComponent.tsx, components/shapediver/appbuilder/AppBuilderActionSetBrowserLocationComponent.tsx, components/shapediver/appbuilder/AppBuilderActionSetParameterValueComponent.tsx, components/shapediver/appbuilder/AppBuilderActionsWidgetComponent.tsx, components/shapediver/appbuilder/AppBuilderWidgetsComponent.tsx, store/useShapeDiverStoreParameters.ts, types/shapediver/appbuilder.ts, types/shapediver/appbuildertypecheck.ts, types/shapediver/export.ts, types/shapediver/parameter.ts, types/store/shapediverStoreParameters.ts
https://shapediver.atlassian.net/browse/SS-7396
=> SS-7396 App Builder actions

components/shapediver/parameter/ParameterGumballComponent.tsx, hooks/shapediver/viewer/interaction/gumball/useGumball.ts
https://shapediver.atlassian.net/browse/SS-7987?focusedCommentId=26752
=> bugfix: gumball matrix duplicate application

components/shapediver/appbuilder/AppBuilderActionAddToCartComponent.tsx, components/shapediver/appbuilder/AppBuilderActionCloseConfiguratorComponent.tsx, components/shapediver/appbuilder/AppBuilderActionsWidgetComponent.tsx, components/shapediver/parameter/ParameterSliderComponent.tsx, components/shapediver/ui/MarkdownWidgetComponent.tsx, hooks/shapediver/appbuilder/useAppBuilderCustomParameters.ts, modules/crosswindowapi/crosswindowapi.ts, modules/crosswindowapi/types/crosswindowapi.ts, modules/ecommerce/ecommerceapi.ts, modules/ecommerce/singleton.ts, modules/ecommerce/types/ecommerceapi.ts, store/useShapeDiverStoreParameters.ts, types/shapediver/appbuilder.ts, types/shapediver/appbuildertypecheck.ts, types/shapediver/parameter.ts, types/store/shapediverStoreParameters.ts, utils/urlbuilder.ts
https://shapediver.atlassian.net/browse/SS-8002
=> SS-8002 cross window (iframe) API setup

components/shapediver/parameter/ParameterColorComponent.tsx, hooks/ui/useCustomTheme.ts, utils/misc/colors.ts
https://shapediver.atlassian.net/browse/SS-8033
Support alpha channel in color pickers
=> SS-8033 color param componets: support for rgba or hexa

hooks/shapediver/appbuilder/useResolveAppBuilderSettings.ts, store/useShapeDiverStorePlatform.ts, types/store/shapediverStorePlatform.ts
https://shapediver.atlassian.net/browse/SS-8036
=> SS-8036 option to disable redirection in case of authentication failure

hooks/shapediver/appbuilder/useAppBuilderCustomParameters.ts, hooks/shapediver/parameters/useParameterHistory.ts, pages/appbuilder/AppBuilderPage.tsx, store/useShapeDiverStoreParameters.ts, types/shapediver/parameter.ts, types/store/shapediverStoreParameters.ts
https://shapediver.atlassian.net/browse/SS-7902
=> SS-7902 parameter history WIP

components/RootComponent.tsx, context/TrackerContext.ts, types/context/trackercontext.ts
https://shapediver.atlassian.net/browse/SS-7678
=> SS-7678 analytics connector

hooks/shapediver/viewer/interaction/selection/useHoverManager.ts, hooks/shapediver/viewer/interaction/selection/useHoverManagerEvents.ts, hooks/shapediver/viewer/interaction/selection/useSelectManager.ts, hooks/shapediver/viewer/interaction/selection/useSelectManagerEvents.ts, hooks/shapediver/viewer/interaction/selection/useSelection.ts, hooks/shapediver/viewer/interaction/useNodeInteractionData.ts
https://shapediver.atlassian.net/browse/SS-7920
@snabela As you can see, this turned out easier than expected. I just pass the ID through to the managers / interaction data so that an assignment can be achieved.
=> SS-7920: enabling multiple selection components at once

components/shapediver/appbuilder/AppBuilderImage.tsx, components/shapediver/appbuilder/widgets/AppBuilderActionsWidgetComponent.tsx, components/shapediver/appbuilder/widgets/AppBuilderTextWidgetComponent.tsx, hooks/shapediver/useKeyBinding.ts, hooks/shapediver/useKeyBindings.ts, hooks/ui/useCustomTheme.ts, hooks/ui/usePropsAppBuilder.ts, pages/templates/AppBuilderAppShellTemplatePage.tsx, pages/templates/AppBuilderContainer.tsx, pages/templates/AppBuilderContainerWrapper.tsx, pages/templates/AppBuilderGridTemplatePage.tsx, pages/templates/AppBuilderHorizontalContainer.tsx, pages/templates/AppBuilderVerticalContainer.tsx
https://shapediver.atlassian.net/browse/SS-8067
=> Improvements to overriding of theme properties per container

store/useShapeDiverStoreParameters.ts, utils/parameterValidation.ts
https://shapediver.atlassian.net/browse/SS-8084
=> SS-8084 add validators for custom parameters

hooks/shapediver/appbuilder/useAppBuilderSettings.ts, store/useShapeDiverStoreViewer.ts, types/shapediver/queryparams.ts, utils/urlbuilder.ts
https://shapediver.atlassian.net/browse/SS-8107
=> SS-8107 Implementing handling of "context" query string parameter

components/shapediver/parameter/ParameterDrawingComponent.tsx, components/shapediver/parameter/ParameterSelectionComponent.tsx
https://shapediver.atlassian.net/browse/SS-8123
@snabela I added a dirty flag within the component to deactivate the confirm button when there is nothing to confirm
=> SS-8123: added inner-component dirty flag

hooks/shapediver/appbuilder/useAppBuilderSettings.ts, types/shapediver/queryparams.ts
https://shapediver.atlassian.net/browse/SS-8133
=> SS-8133 Set parameter values from query string

components/shapediver/appbuilder/widgets/AppBuilderTextWidgetComponent.tsx
https://shapediver.atlassian.net/browse/SS-7979
=> SS-7979 horizontal scrolling for text widgets

components/shapediver/parameter/ParameterDrawingComponent.tsx
https://shapediver.atlassian.net/browse/SS-8138
=> SS-8138: drawing tools mobile check

store/useShapeDiverStoreParameters.ts
https://shapediver.atlassian.net/browse/SS-8175
@snabela as discussed, this works now as expected!
=> SS-8175: setting of uiValue and execValue for custom parameters

components/shapediver/parameter/ParameterGumballComponent.tsx, hooks/shapediver/viewer/interaction/gumball/useGumball.ts
https://shapediver.atlassian.net/browse/SS-8140
There was an issue in which nodes where selected.
As I didn't find it at first, I did some "accidental" cleanup haha
=> SS-8140: fixed transformation issue and made some simplifications

components/shapediver/parameter/ParameterDraggingComponent.tsx, hooks/shapediver/viewer/drawing/useRestrictions.ts, hooks/shapediver/viewer/interaction/dragging/useDragManager.ts, hooks/shapediver/viewer/interaction/dragging/useDragManagerEvents.ts, hooks/shapediver/viewer/interaction/dragging/useDragging.tsx, hooks/shapediver/viewer/interaction/gumball/useGumball.ts, hooks/shapediver/viewer/interaction/useCreateNameFilterPattern.ts, types/components/shapediver/componentTypes.ts
https://shapediver.atlassian.net/browse/SS-8146
This seems to now work really well, but it has to be tested again once https://shapediver.atlassian.net/browse/SS-8175 is fixed. You can see the dirty workarounds I did for now, so this should not be merged until the other task is resolved 😂
=> SS-8146: dragging in App Builder

components/shapediver/appbuilder/actions/AppBuilderActionAddToCartComponent.tsx, components/shapediver/appbuilder/actions/AppBuilderActionCloseConfiguratorComponent.tsx, components/shapediver/appbuilder/actions/AppBuilderActionCreateModelStateComponent.tsx, components/shapediver/parameter/ParameterDrawingComponent.tsx, components/ui/NotificationWrapper.tsx, context/NotificationContext.ts, hooks/shapediver/useSession.ts, hooks/shapediver/useSessions.ts, hooks/shapediver/viewer/drawing/useDrawingToolsEvents.ts, hooks/shapediver/viewer/interaction/selection/useSelectManagerEvents.ts, hooks/ui/useCustomTheme.ts, hooks/useErrorReporting.ts, store/useShapeDiverStoreParameters.ts, store/useShapeDiverStoreViewer.ts, types/context/notificationcontext.ts, types/errorReporting.ts, types/store/shapediverStoreParameters.ts, types/store/shapediverStoreViewer.ts
@MajorMeerkatThe3rd contains a bit more stuff than originally planned ;-) 
I refactored notifications, and established a mechanism for error reporting in general. Will be useful for several things in the near future. I will merge this right away, because the main repo also requires a dependent change.
=> SS-8131 App Builder turns white in case of a computation timeout

components/shapediver/appbuilder/actions/AppBuilderActionComponent.tsx, components/shapediver/exports/ExportLabelComponent.tsx, components/shapediver/parameter/ParameterLabelComponent.tsx, components/shapediver/parameter/ParameterSliderComponent.tsx, components/shapediver/platform/ModelCardOverlay.tsx, components/shapediver/platform/ModelStatusIcon.tsx, components/shapediver/ui/DrawingOptionsComponent.tsx, components/shapediver/ui/MarkdownWidgetComponent.tsx, components/shapediver/viewport/ViewportIcons.tsx, components/ui/TabsComponent.tsx, components/ui/ToggleIcon.tsx, components/ui/TooltipWrapper.tsx, hooks/ui/useCustomTheme.ts
https://shapediver.atlassian.net/browse/SS-8092
Example screenshot: https://shapediver.atlassian.net/browse/SS-8092?focusedCommentId=28795
=> SS-8092 improved tooltips

components/shapediver/parameter/ParameterDraggingComponent.tsx, components/shapediver/parameter/ParameterDrawingComponent.tsx, components/shapediver/parameter/ParameterGumballComponent.tsx, components/shapediver/parameter/ParameterInteractionComponent.module.css, components/shapediver/parameter/ParameterSelectionComponent.tsx
https://shapediver.atlassian.net/browse/SS-8148
implementation of the prompt and styling fixes and merges
now the wrapping of the text works as well
FYI: you accidentally created a branch with the same task number at some point. just to avoid the confusion 😂
=> SS-8148: prompt options and styling

components/shapediver/appbuilder/widgets/AppBuilderWidgetsComponent.tsx, context/ComponentContext.ts, types/components/shapediver/componentTypes.ts, types/context/componentcontext.ts
https://shapediver.atlassian.net/browse/SS-8291
preparation for the attribute vis widget
As for the Attribute Visualization we need a widget that is directly depending on the viewer, we need to also add context options for the widgets.
I also changed the context a bit so that you only have to provide the components that you want to change compared to the default.
=> SS-8291: added widget to context and simplified defaults

context/TrackerContext.ts, types/context/trackercontext.ts
https://shapediver.atlassian.net/browse/SS-7679
=> SS-7679 support for pageview tracking of properties that are not available immediately

hooks/shapediver/useCreateModelState.ts, hooks/shapediver/viewer/useViewport.ts, types/context/componentcontext.ts, types/store/shapediverStoreViewportAccessFunctions.ts
https://shapediver.atlassian.net/browse/SS-8351
I needed to make it possible to provide an async screenshot for webGi
=> SS-8351: changes needed to allow async screenshot

components/shapediver/appbuilder/AppBuilderImage.tsx, components/shapediver/appbuilder/widgets/AppBuilderImageExportWidgetComponent.tsx, components/shapediver/appbuilder/widgets/AppBuilderImageWidgetComponent.tsx, components/ui/Svg.tsx, types/shapediver/appbuilder.ts, types/shapediver/appbuildertypecheck.ts
https://shapediver.atlassian.net/browse/SS-8380
=> SS-8380: Add svg support

components/shapediver/ui/ParametersAndExportsAccordionComponent.tsx, hooks/ui/useCustomTheme.ts
https://shapediver.atlassian.net/browse/SS-8442
=> SS-8442 identify groups by name instead of id

components/ui/Svg.tsx
https://shapediver.atlassian.net/browse/SS-8380
=> SS-8380: Add SVG unmount clean

components/shapediver/parameter/ParameterDraggingComponent.tsx, components/shapediver/parameter/ParameterGumballComponent.tsx, components/shapediver/parameter/ParameterSelectionComponent.tsx
=> SS-8452: reset internal data once the parameter definition changed

hooks/shapediver/viewer/drawing/useDrawingToolsApi.ts
https://shapediver.atlassian.net/browse/SS-8461
@snabela FYI
=> SS-8461: fixed issue where drawing tools options are not correctly set

components/shapediver/parameter/ParameterDraggingComponent.tsx, components/shapediver/parameter/ParameterDrawingComponent.tsx, components/shapediver/parameter/ParameterGumballComponent.tsx, components/shapediver/parameter/ParameterSelectionComponent.tsx
https://shapediver.atlassian.net/browse/SS-8478
=> SS-8478: parsing of correct values

hooks/shapediver/viewer/useViewport.ts
https://shapediver.atlassian.net/browse/SS-8476
=> SS-8476: gltf conversion request crash

components/shapediver/appbuilder/actions/AppBuilderActionAddToCartComponent.tsx, components/shapediver/appbuilder/actions/AppBuilderActionComponent.tsx, components/shapediver/appbuilder/actions/AppBuilderActionCreateModelStateComponent.tsx, components/shapediver/ui/ParametersAndExportsAccordionComponent.tsx, hooks/shapediver/useCreateModelState.ts, hooks/shapediver/useKeyBindings.ts, modules/ecommerce/types/ecommerceapi.ts
https://shapediver.atlassian.net/browse/SS-8280
=> SS-8280 pass model state image along with add to cart message

components/shapediver/viewport/ViewportIcons.module.css, components/shapediver/viewport/ViewportIcons.tsx
https://shapediver.atlassian.net/browse/SS-8456
=> SS-8456: Add adaptive icons color

components/shapediver/viewport/ViewportComponent.tsx, hooks/shapediver/appbuilder/useAppBuilderSettings.ts, hooks/shapediver/appbuilder/useSessionWithAppBuilder.ts, pages/appbuilder/AppBuilderPage.tsx
@snabela first multiple sessions commit to review
as discussed, not much on the AB side
=> SS-8451: working multiple session support

components/shapediver/parameter/ParameterSelectComponent.tsx, components/shapediver/parameter/select/SelectButtonFlexComponent.tsx, components/shapediver/parameter/select/SelectButtonGroupComponent.tsx, components/shapediver/parameter/select/SelectChipGroupComponent.tsx, components/shapediver/parameter/select/SelectColorComponent.module.css, components/shapediver/parameter/select/SelectColorComponent.tsx, components/shapediver/parameter/select/SelectComponent.tsx, components/shapediver/parameter/select/SelectDropDownComponent.tsx, components/shapediver/parameter/select/SelectFullWidthCards.module.css, components/shapediver/parameter/select/SelectFullWidthCards.tsx, components/shapediver/parameter/select/SelectImageDropDownComponent.tsx, hooks/ui/useCustomTheme.ts
https://shapediver.atlassian.net/browse/SS-8076
corresponding PR: https://github.com/shapediver/AppBuilderSdk/pull/105
=> SS-8076 stringlist parameter extensions

store/useShapeDiverStorePlatform.ts
https://shapediver.atlassian.net/browse/SS-8548
=> SS-8548 Pass on "provider" query string parameter

components/shapediver/appbuilder/widgets/AppBuilderAgentWidgetComponent.tsx, hooks/shapediver/appbuilder/useAgent.ts
https://shapediver.atlassian.net/browse/SS-8562
=> SS-8562 prompt engineering

hooks/shapediver/useSessions.ts, pages/appbuilder/AppBuilderPage.tsx, store/useShapeDiverStoreSession.ts, types/store/shapediverStoreSession.ts
https://shapediver.atlassian.net/browse/SS-8535
As discussed, should work now as expected!
=> SS-8535: improved session loading

components/shapediver/appbuilder/widgets/AppBuilderAgentWidgetComponent.tsx, hooks/shapediver/appbuilder/useAgent.ts, utils/misc/colors.ts
https://shapediver.atlassian.net/browse/SS-8562
=> SS-8562 prompt refinements, color parameter support

components/shapediver/exports/ExportButtonComponent.tsx, types/shapediver/export.ts
https://shapediver.atlassian.net/browse/SS-8566
=> SS-8566 export button improvements

components/shapediver/parameter/select/SelectCarouselComponent.module.css, components/shapediver/parameter/select/SelectCarouselComponent.tsx, components/shapediver/parameter/select/SelectColorComponent.tsx, components/shapediver/parameter/select/SelectComponent.tsx, components/shapediver/parameter/select/SelectFullWidthCards.module.css, components/shapediver/parameter/select/SelectFullWidthCards.tsx, components/shapediver/parameter/select/SelectImageDropDownComponent.tsx, components/ui/Icon.tsx, components/ui/TextWeighted.tsx, components/ui/TooltipWrapper.tsx, hooks/ui/useCustomTheme.ts, types/shapediver/icons.ts
https://shapediver.atlassian.net/browse/SS-8552
=> SS-8552: Add select carousel component

components/shapediver/ui/DrawingOptionsComponent.tsx, hooks/shapediver/viewer/drawing/useDrawingToolsApi.ts, store/useDrawingOptionsStore.ts
https://shapediver.atlassian.net/browse/SS-8489
@snabela FYI
=> SS-8489: removed grid unit and angle step sliders

store/useShapeDiverStoreParameters.ts, types/store/shapediverStoreParameters.ts
https://shapediver.atlassian.net/browse/SS-8645
=> SS-8645 hybrid accept/reject behaviour

components/shapediver/appbuilder/AppBuilderFallbackContainerComponent.tsx, components/shapediver/appbuilder/widgets/AppBuilderAccordionWidgetComponent.tsx, components/shapediver/parameter/ParameterBooleanComponent.tsx, components/shapediver/parameter/ParameterColorComponent.tsx, components/shapediver/parameter/ParameterDraggingComponent.tsx, components/shapediver/parameter/ParameterDrawingComponent.tsx, components/shapediver/parameter/ParameterFileInputComponent.tsx, components/shapediver/parameter/ParameterGumballComponent.tsx, components/shapediver/parameter/ParameterLabelComponent.tsx, components/shapediver/parameter/ParameterSelectComponent.tsx, components/shapediver/parameter/ParameterSelectionComponent.tsx, components/shapediver/parameter/ParameterSliderComponent.tsx, components/shapediver/parameter/ParameterStringComponent.tsx, components/shapediver/parameter/ParameterWrapperComponent.module.css, components/shapediver/parameter/ParameterWrapperComponent.tsx, components/shapediver/ui/ParametersAndExportsAccordionComponent.tsx, components/shapediver/ui/ViewportAcceptRejectButtons.tsx, hooks/ui/useCustomTheme.ts, pages/appbuilder/AppBuilderPage.tsx, types/components/shapediver/propsParameter.ts, types/context/componentcontext.ts, types/shapediver/appbuilder.ts
https://shapediver.atlassian.net/browse/SS-8557
=> SS-8557 updates to the accept/reject behaviour

components/shapediver/parameter/select/ButtonImageCard.module.css, components/shapediver/parameter/select/ButtonImageCard.tsx, components/shapediver/parameter/select/SelectCarouselComponent.module.css, components/shapediver/parameter/select/SelectCarouselComponent.tsx, components/shapediver/parameter/select/SelectComponent.tsx, components/shapediver/parameter/select/SelectGridComponent.tsx, hooks/ui/useCustomTheme.ts
https://shapediver.atlassian.net/browse/SS-8674
=> SS-8674: Add grid select

components/shapediver/viewport/ViewportComponent.tsx, hooks/shapediver/appbuilder/useAppBuilderInstances.ts, hooks/shapediver/appbuilder/useSessionWithAppBuilder.ts, hooks/shapediver/useSession.ts, hooks/shapediver/viewer/interaction/useNodeInteractionData.ts, hooks/shapediver/viewer/useViewport.ts, store/useShapeDiverStoreInstances.ts, store/useShapeDiverStoreParameters.ts, store/useShapeDiverStoreProcessManager.ts, store/useShapeDiverStoreSession.ts, types/store/shapediverStoreInstances.ts, types/store/shapediverStoreProcessManager.ts
https://shapediver.atlassian.net/browse/SS-8638
@snabela FYI
=> SS-8638: general fixes and improvements for instancing

components/shapediver/ui/MarkdownWidgetComponent.module.css, components/shapediver/ui/MarkdownWidgetComponent.tsx
https://shapediver.atlassian.net/browse/SS-8682
=> SS-8682: Markdown normalize

components/shapediver/exports/ExportButtonComponent.tsx, components/shapediver/ui/ParametersAndExportsAccordionComponent.module.css, components/shapediver/ui/ParametersAndExportsAccordionComponent.tsx, hooks/ui/useCustomTheme.ts
https://shapediver.atlassian.net/browse/SS-8707
=> SS-8707: Styles improvements

components/shapediver/appbuilder/actions/AppBuilderActionSetBrowserLocationComponent.tsx, components/shapediver/appbuilder/widgets/AppBuilderActionsWidgetComponent.tsx
https://shapediver.atlassian.net/browse/SS-8725
=> SS-8725 Set browser location action: optionally create model state

components/shapediver/parameter/select/SelectImageDropDownComponent.module.css, components/shapediver/parameter/select/SelectImageDropDownComponent.tsx
https://shapediver.atlassian.net/browse/SS-8697
@snabela that's prototype to check - do we need it or not.
=> SS-8697: Add image and description to select image dropdown

components/shapediver/appbuilder/actions/AppBuilderActionAddToCartComponent.tsx, components/shapediver/appbuilder/actions/AppBuilderActionCreateModelStateComponent.tsx, components/shapediver/appbuilder/actions/AppBuilderActionSetBrowserLocationComponent.tsx, hooks/shapediver/useCreateModelState.ts, hooks/shapediver/useKeyBindings.ts, hooks/ui/useCustomTheme.ts, types/shapediver/appbuilder.ts, types/shapediver/appbuildertypecheck.ts
https://shapediver.atlassian.net/browse/SS-8722
=> SS-8722 Optionally omit "context" and other parameter values when creating model states

store/useShapeDiverStoreParameters.ts
https://shapediver.atlassian.net/browse/SS-8391
=> SS-8391 prevent repeated file uploads

components/shapediver/parameter/select/SelectImageDropDownComponent.module.css, components/shapediver/parameter/select/SelectImageDropDownComponent.tsx
https://shapediver.atlassian.net/browse/SS-8697?focusedCommentId=38452
=> SS-8697 improve SelectImageDropDownComponent borders

components/shapediver/appbuilder/actions/AppBuilderActionComponent.tsx, components/shapediver/ui/ParametersAndExportsAccordionComponent.module.css, components/shapediver/ui/ParametersAndExportsAccordionComponent.tsx, hooks/ui/useCustomTheme.ts
https://shapediver.atlassian.net/browse/SS-8707?focusedCommentId=38530
=> SS-8707 UI improvements

components/shapediver/parameter/ParameterSelectComponent.tsx, components/shapediver/parameter/ParameterSelectionComponent.tsx, components/shapediver/parameter/select/SelectComponent.tsx, types/shapediver/appbuilder.ts, types/shapediver/appbuildertypecheck.ts
https://shapediver.atlassian.net/browse/SS-8762
=> SS-8762 dynamic StringList parameters with images

components/shapediver/outputs/OutputChunkComponent.tsx, components/shapediver/parameter/ParameterLabelComponent.tsx, components/shapediver/parameter/ParameterStargateComponent.tsx, hooks/shapediver/stargate/useStargateOutput.ts, hooks/shapediver/stargate/useStargateParameter.ts, store/useShapeDiverStoreStargate.ts, types/store/shapediverStoreStargate.ts
https://shapediver.atlassian.net/browse/SS-8723
=> SS-8723 Desktop clients support in App Builder

components/shapediver/ui/MarkdownWidgetComponent.tsx
https://shapediver.atlassian.net/browse/SS-8789
=> SS-8789: Extend markdown by sup, sub and ins

components/shapediver/exports/ExportButtonComponent.tsx, components/shapediver/exports/ExportLabelComponent.tsx, components/shapediver/outputs/OutputChunkComponent.tsx, components/shapediver/parameter/ParameterFileInputComponent.tsx, components/shapediver/parameter/ParameterLabelComponent.tsx, components/shapediver/parameter/ParameterStargateComponent.tsx, components/shapediver/stargate/DesktopClientPanel.tsx, components/shapediver/stargate/StargateInput.tsx, components/ui/Icon.tsx, hooks/shapediver/appbuilder/useAgent.ts, hooks/shapediver/parameters/useAllParametersStateless.ts, hooks/shapediver/stargate/useStargateBakeData.ts, hooks/shapediver/stargate/useStargateExport.ts, hooks/shapediver/stargate/useStargateExportFile.ts, hooks/shapediver/stargate/useStargateGetData.ts, hooks/shapediver/stargate/useStargateOutput.ts, hooks/shapediver/stargate/useStargateParameter.ts, store/useShapeDiverStoreParameters.ts, types/shapediver/icons.ts, types/shapediver/parameter.ts, types/shapediver/stargate.ts, types/store/shapediverStoreParameters.ts
https://shapediver.atlassian.net/browse/SS-8812
=> SS-8812 support for file inputs and exports

components/shapediver/appbuilder/widgets/AppBuilderAreaChartWidgetComponent.tsx, components/shapediver/appbuilder/widgets/AppBuilderAttributeVisualizationWidgetComponent.tsx, components/shapediver/appbuilder/widgets/AppBuilderBarChartWidgetComponent.tsx, components/shapediver/appbuilder/widgets/AppBuilderLineChartWidgetComponent.tsx, components/shapediver/appbuilder/widgets/AppBuilderRoundChartWidgetComponent.tsx, components/shapediver/appbuilder/widgets/attributes/NumberAttribute.tsx, components/shapediver/appbuilder/widgets/attributes/StringAttribute.tsx, hooks/ui/useCustomTheme.ts
https://shapediver.atlassian.net/browse/SS-8784
@snabela I just now only did this for the AV, please confirm if you like it that way before I also do that for other files
=> SS-8784: Improve theme capabilities for currently unsupported properties

components/shapediver/parameter/ParameterDraggingComponent.tsx, components/shapediver/parameter/ParameterDrawingComponent.tsx, components/shapediver/parameter/ParameterGumballComponent.tsx, components/shapediver/parameter/ParameterSelectComponent.tsx, components/shapediver/parameter/ParameterSelectionComponent.tsx
https://shapediver.atlassian.net/browse/SS-8783
I now added notifications as well.
=> SS-8783: notifications for validation errors

components/shapediver/ui/ParametersAndExportsAccordionComponent.tsx, hooks/ui/useCustomTheme.ts
https://shapediver.atlassian.net/browse/SS-8750
=> SS-8750 style update for accordions

components/shapediver/parameter/ParameterSelectComponent.tsx
https://shapediver.atlassian.net/browse/SS-8836
=> SS-8836: Fix empty value

hooks/shapediver/appbuilder/useAppBuilderCustomParameters.ts
https://shapediver.atlassian.net/browse/SS-8844
To avoid further confusion of this, feel free to adjust the message.
=> SS-8844: notification if the app builder data is too large

components/shapediver/ui/MarkdownWidgetComponent.tsx
https://shapediver.atlassian.net/browse/SS-8850
=> SS-8850: Add markdown overline

components/shapediver/appbuilder/actions/AppBuilderActionSetParameterValueComponent.tsx
https://shapediver.atlassian.net/browse/SS-8847?focusedCommentId=43579
=> SS-8847: Fix action button availability

components/shapediver/parameter/select/SelectChipGroupComponent.tsx
https://shapediver.atlassian.net/browse/SS-8848
=> SS-8848: Fix empty group state

hooks/shapediver/stargate/useStargateBakeData.ts, hooks/shapediver/stargate/useStargateExport.ts, hooks/shapediver/stargate/useStargateExportFile.ts, hooks/shapediver/stargate/useStargateGetData.ts, hooks/shapediver/stargate/useStargateOutput.ts, hooks/shapediver/stargate/useStargateParameter.ts, store/useShapeDiverStoreStargate.ts, types/shapediver/stargate.ts, types/store/shapediverStoreStargate.ts
https://shapediver.atlassian.net/browse/SS-8834
=> SS-8834: Make stargate lazy loaded

hooks/ui/useCustomTheme.ts
https://shapediver.atlassian.net/browse/SS-8819?focusedCommentId=43848
Mantine's 7 default image css restored.
=> SS-8819: Restore image behavior

components/shapediver/viewport/ViewportIcons.tsx, hooks/ui/useCustomTheme.ts, types/shapediver/viewportIcons.ts
https://shapediver.atlassian.net/browse/SS-8827?focusedCommentId=44179
@MajorMeerkatThe3rd I've fixed 1st and 3rd items. (Except On mobile (android and iOS) the buttons only get activated on a single press)
=> SS-8827: Mobile touch events and modal visibility

hooks/shapediver/appbuilder/useAppBuilderSettings.ts, hooks/shapediver/appbuilder/useResolveAppBuilderSettings.ts
https://shapediver.atlassian.net/browse/SS-8899
@snabela took a bit to figure this out. The main issue was that the sessions were not properly memoized, especially when a JSON was loaded. I now wait for the JSON to load and then continue.
I also did some further improvements. As this is a critical part, I think a review makes sense
=> SS-8899: Duplicate platform calls

store/useShapeDiverStoreParameters.ts
https://shapediver.atlassian.net/browse/SS-8898
The last PR before we can deploy App Builder 1.3
=> SS-8898 parameter batch update: warn instead of throw

hooks/shapediver/appbuilder/useResolveAppBuilderSettings.ts, store/useShapeDiverStorePlatformModels.ts, store/useShapeDiverStorePlatformSavedStates.ts, types/store/shapediverStorePlatformGeneric.ts, types/store/shapediverStorePlatformSavedStates.ts, utils/platform/filter.ts
Preparation for task https://shapediver.atlassian.net/browse/SS-7401
For comparison please see how the already existing model store is used here: https://github.com/shapediver/AppBuilderShared/blob/021b79e1ae4d6293514a4e77bf8201e479e0fbdf/components/shapediver/platform/ModelLibrary.tsx#L33
=> SS-7401 saved state store

hooks/shapediver/appbuilder/useAppBuilderCustomParameters.ts, pages/appbuilder/AppBuilderPage.tsx
https://shapediver.atlassian.net/browse/SS-8935
@snabela I tested this and it works now very well, even with instances
=> SS-8935 fixed history for instances

components/shapediver/parameter/ParameterSelectComponent.tsx, components/shapediver/parameter/select/SelectComponent.tsx, components/shapediver/parameter/select/SelectDropDownComponent.tsx, types/shapediver/appbuilder.ts, types/shapediver/appbuildertypecheck.ts
https://shapediver.atlassian.net/browse/SS-8989
=> SS-8989: Add select searchable

components/shapediver/parameter/ParameterSliderComponent.tsx, types/shapediver/appbuilder.ts, types/shapediver/appbuildertypecheck.ts
https://shapediver.atlassian.net/browse/SS-8988
=> SS-8988 optionally define step using overrides

components/shapediver/appbuilder/widgets/AppBuilderDesktopClientSelectionWidgetComponent.tsx, components/shapediver/stargate/DesktopClientPanel.tsx, hooks/ui/useCustomTheme.ts, types/shapediver/appbuilder.ts, types/shapediver/appbuildertypecheck.ts
https://shapediver.atlassian.net/browse/SS-8994
=> SS-8994 new stargate desktop client selection props and behaviour

components/shapediver/parameter/select/SelectComponent.tsx, components/shapediver/parameter/select/SelectFullWidthCards.tsx, components/shapediver/parameter/select/SelectFullWidthCardsAsyncComponent.tsx, components/shapediver/parameter/select/SelectGridAsyncComponent.tsx, components/shapediver/parameter/select/SelectGridComponent.tsx, hooks/shapediver/parameters/select/useAsync.ts, hooks/shapediver/parameters/select/useSelectAsync.ts, hooks/ui/useCustomTheme.ts
https://shapediver.atlassian.net/browse/SS-8997
=> SS-8997 async version of "grid" and "fullwidthcards" select components

components/shapediver/platform/ModelCard.module.css, components/shapediver/platform/ModelCard.tsx, components/shapediver/platform/ModelCardOverlay.tsx, components/shapediver/platform/ModelCardOverlayWrapper.tsx, components/shapediver/ui/OverlayWrapper.tsx, components/ui/Icon.tsx, hooks/shapediver/appbuilder/useAppBuilderSettings.ts, pages/platform/LibraryPage.tsx, store/useShapeDiverStoreParameters.ts, types/context/componentcontext.ts, types/shapediver/output.ts
https://shapediver.atlassian.net/browse/SS-8769
Corresponding PR: https://github.com/shapediver/AppBuilderPERI/pull/3
=> SS-8769 custom model card overlay

components/shapediver/ui/SelectedAttributeComponent.module.css, components/shapediver/ui/SelectedAttributeComponent.tsx, components/shapediver/viewport/ViewportIcons.tsx, components/shapediver/viewport/anchors/ViewportAnchor3d.tsx, components/shapediver/viewport/anchors/shared/AnchorContainer.tsx, components/shapediver/viewport/buttons/ViewportIconButton.tsx, hooks/shapediver/viewer/useViewportAnchors.tsx, types/shapediver/appbuilder.ts, types/shapediver/appbuildertypecheck.ts
https://shapediver.atlassian.net/browse/SS-9001
=> SS-9001: anchor refinements

components/shapediver/parameter/select/SelectFullWidthCards.module.css, components/shapediver/parameter/select/SelectFullWidthCards.tsx, components/shapediver/parameter/select/SelectGridComponent.module.css, components/shapediver/parameter/select/SelectGridComponent.tsx
https://shapediver.atlassian.net/browse/SS-8997?focusedCommentId=47182
=> SS-8997: Pin searchbar

hooks/shapediver/viewer/interaction/gumball/useGumball.ts
https://shapediver.atlassian.net/browse/SS-9021
=> SS-9021: make use of gumball restrictions

components/shapediver/appbuilder/widgets/AppBuilderImageExportWidgetComponent.tsx, components/shapediver/exports/ExportButtonComponent.tsx, components/shapediver/exports/ExportLabelComponent.tsx, hooks/shapediver/parameters/useExport.ts
https://shapediver.atlassian.net/browse/SS-8798
=> SS-8798: Fix missing export error

hooks/shapediver/appbuilder/useAppBuilderCustomParameters.ts
https://shapediver.atlassian.net/browse/SS-9018
=> SS-9018: Fix undo button

components/shapediver/appbuilder/widgets/AppBuilderAccordionUiWidgetComponent.tsx, components/shapediver/ui/MarkdownWidgetComponent.module.css
https://shapediver.atlassian.net/browse/SS-9062
=> SS-9062: UI improvements

types/shapediver/appbuildertypecheck.ts
https://shapediver.atlassian.net/browse/SS-9054?focusedCommentId=48368
=> SS-9054: Extend validation type

components/shapediver/viewport/anchors/ViewportAnchor3d.tsx, types/shapediver/appbuilder.ts, types/shapediver/appbuildertypecheck.ts
https://shapediver.atlassian.net/browse/SS-9075
=> SS-9075: exposed hideable property
